In [ ]:
import numpy as np
list_array_1 = np.array([1,7,3,4,9])
list_array_1
#Создание массива

array([1, 2, 3, 4])

In [51]:
list_array_1.shape
#Демонстрация размерности

(4,)

In [52]:
list_array_2 = np.array([[[1.9,4.6,3.8,4],[2,5,4.8,1.1]],[[2.5,4.6,5.8,0],[3,7.3,2.5,6.9]]])
list_array_2
#Создание трехмерного массива

array([[[1.9, 4.6, 3.8, 4. ],
        [2. , 5. , 4.8, 1.1]],

       [[2.5, 4.6, 5.8, 0. ],
        [3. , 7.3, 2.5, 6.9]]])

In [53]:
list_array_2.dtype
#Демонстрация формы

dtype('float64')

In [54]:
list_array_2.shape

(2, 2, 4)

In [55]:
zeros_array = np.zeros((12))
zeros_array
#Создание массива из нулей

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [56]:
zeros_matrix = np.zeros((2,2))
zeros_matrix

array([[0., 0.],
       [0., 0.]])

In [57]:
ones_array = np.ones(3)
ones_array
#Создание массива из единиц

array([1., 1., 1.])

In [58]:
ones_matrix = np.ones((2,2))
ones_matrix

array([[1., 1.],
       [1., 1.]])

In [59]:
eye_matrix = np.eye(4)
eye_matrix
#Создание единичной матрицы

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [60]:
arange_massive = np.arange(5,7.2,0.2)
arange_massive

array([5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. ])

In [61]:
empt = np.empty(2)
empt

array([5.43230922e-312, 7.29112202e-304])

In [62]:
a = np.array([1,2,3,4,5,5,10])

a[-1::-1]
#Пример использования среза для выведения массива в обратном порядке

array([10,  5,  5,  4,  3,  2,  1])

In [63]:
a[::2]
#Использование среза для возвращения значений с четными индексами

array([ 1,  3,  5, 10])

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,6],[1,0]])
c = a*b
c
#Поэлементное умножение матриц

array([[ 4, 12],
       [ 3,  0]])

In [71]:
#Поэлементное сложение матриц
c = a+b
c

array([[5, 8],
       [4, 4]])

In [72]:
#Унможение матрицы на скаляр
a*5

array([[ 5, 10],
       [15, 20]])

In [ ]:
#Перемножение матриц
a@b

array([[ 6,  6],
       [16, 18]])

In [74]:
np.dot(a,b)

array([[ 6,  6],
       [16, 18]])

In [ ]:
#Нахождение среднего значения в массиве
np.median(list_array_1)

np.float64(2.5)

In [ ]:
#Стандартное отклонение
np.std(list_array_1)

np.float64(1.118033988749895)

In [82]:
#Дисперсия
np.var(list_array_1)

np.float64(1.25)

In [ ]:
#Дисперсия может вычисляться и для многомерных массивов
np.var(a)

np.float64(1.25)